### ISSUE TITLE
OS:WIN XP can not find php.exe

### ISSUE THREAD

**Issue by kuxiongxiong** [welovewordpress/SublimeHtmlTidy#1]
error info:
HtmlTidy cannot find php.exe. Make sure it is available in your PATH.
I DO Installed php-the package WAMP5

**Comment by welovewordpress** [comment]
Thanks for your feedback, feiqiao.

Could you please enter `php.exe -v` on your command line and tell me the response? If this gives you any error message, then `php.exe` is not in your `PATH`.

I will publish an update for HtmlTidy soon where you can set up the path to your `php.exe` in its settings file. Until then, the plugin relies on windows (the command shell) to find php.exe.

**Comment by kuxiongxiong** [comment]
error :bad commond

**Comment by welovewordpress** [comment]
Ok, so it's not in your PATH. That we figured out.

But since Windows itself is unable to find `php.exe` you need to find it. It seems that on WAMP the actual path depends on the installed version of PHP, so for PHP 5.2.5 it would look like this:

```
C:\wamp\bin\php\php5.2.5\php.exe
```

Could you find the correct path on _your_ system, please? Then I can publish an update which will include a few default paths HtmlTidy will automatically search in.

**Comment by kuxiongxiong** [comment]
my Path:

D:\Program Files\wamp\php\php.exe

**Comment by welovewordpress** [comment]
I just updated the package. The plugin now contains a list of possible locations for php.exe which it will try one by one until it finds it. I included your custom location `D:\Program Files\wamp\php\php.exe` so it should work for you now.

The next version will include a setting to specify a custom path to php.exe manually. But I will keep the list of possible locations to make it work "out of the box" for more users.

If you are uncertain if you got the latest version, you can just uninstall HtmlTidy and install it again. If the update check of Sublime Text was already done within the last hour, you will have to go this way.

**Comment by welovewordpress** [comment]
@feiqiao is it working for you now? then I can close the issue...

**Comment by kuxiongxiong** [comment]
sorry.I'm late,my php.exe path is D:\Program Files\wamp\php\php.exe,
After updated package,it still doesn't work ..

**Comment by welovewordpress** [comment]
I now bundled the native windows `tidy.exe` with the plugin. In theory, it should work now and doesn't require any specific php version anymore.
